// loans.js

var db = require('../config.js');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var loanSchema = new Schema({
  id: Number,
  memberId: Number,
  loanAmount: Number,
  fundedAmount: Number,
  term: Number,
  intRate: Number,
  expDefaultRate: Number,
  serviceFeeRate: Number,
  installment: Number,
  grade: String,
  subGrade: String,
  empLength: Number,
  homeOwnership: String,
  annualInc: Number,
  isIncV: String,
  acceptD: Date,
  expD: Date,
  listD: Date,
  creditPullD: Date,
  reviewStatusD: String,
  reviewStatus: String,
  desc: String,
  purpose: String,
  addrZip: String,
  addrState: String,
  investorCount: Number,
  ilsExpD: String,
  initialListStatus: String,
  empTitle: String,
  accNowDelinq: Number,
  accOpenPast24Mths: Number,
  bcOpenToBuy: Number,
  percentBcGt75: Number,
  bcUtil: Number,
  dti: Number,
  delinq2Yrs: Number,
  delinqAmnt: Number,
  earliestCrLine: Date,
  ficoRangeLow:Number,
  ficoRangeHigh:Number,
  inqLast6Mths:Number,
  mthsSinceLastDelinq:Number,
  mthsSinceLastRecord:Number,
  mthsSinceRecentInq:Number,
  mthsSinceRecentRevolDelinq:Number,
  mthsSinceRecentBc:Number,
  mortAcc:Number,
  openAcc:Number,
  pubRec:Number,
  totalBalExMort:Number,
  revolBal:Number,
  revolUtil:Number,
  totalBcLimit:Number,
  totalAcc:Number,
  totalIlHighCreditLimit:Number,
  numRevAccts:Number,
  mthsSinceRecentBcDlq:Number,
  pubRecBankruptcies:Number,
  numAcctsEver120Ppd:Number,
  chargeoffWithin12Mths:Number,
  collections12MthsExMed:Number,
  taxLiens:Number,
  mthsSinceLastMajorDerog:Number,
  numSats:Number,
  numTlOpPast12m:Number,
  moSinRcntTl:Number,
  totHiCredLim:Number,
  totCurBal:Number,
  avgCurBal:Number,
  numBcTl:Number,
  numActvBcTl:Number,
  numBcSats:Number,
  pctTlNvrDlq:Number,
  numTl90gDpd24m:Number,
  numTl30dpd:Number,
  numTl120dpd2m:Number,
  numIlTl:Number,
  moSinOldIlAcct:Number,
  numActvRevTl:Number,
  moSinOldRevTlOp:Number,
  moSinRcntRevTlOp:Number,
  totalRevHiLim:Number,
  numRevTlBalGt0:Number,
  numOpRevTl:Number,
  totCollAmt:Number
});

var Loans = mongoose.model('Loans', loanSchema);

module.exports = Loans;
